export enum ENUM_SETTING_DATA_TYPE {
    BOOLEAN = 'BOOLEAN',
    DATE = 'DATE',
    ARRAY_OF_STRING = 'ARRAY_OF_STRING',
    NUMBER = 'NUMBER',
    ARRAY_OF_MAP = 'ARRAY_OF_MAP',
    PERCENTAGE = 'PERCENTAGE',
}
